#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: identify_customer
    permanent: true
