#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: identify_customer
    permanent: true

admin:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: admin_booking_index
    permanent: true
